### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by YusukeIwaki** [YusukeIwaki/Rocket.Chat.Android.Lily#1]
## Key Result

* Successful login.
* Remove unwanted splash screen.

## Todo

* [ ] define a model to keep the status of logged-in?.
* [ ] implement logged-in? check. BaseActivity

## Test

* [ ] Login with email/password
* [ ] Login with GitHub
